/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "void-black": "#000000",
        "ground-iron": "#181818",
        "carbon-veil": "#212525",
        "circuit-border": "#485346",
        "phosphor-blue-black": "#1f2a33",
        "charcoal-rust": "#231c1c",
        "lime-pulse": "#7fee64",
        "phosphor-white": "#ddffdc",
        "mint-frost": "#def0dd",
        "sage-60": "#8cab87",
        "sage-40": "#677d64",
        "moss-70": "#9cbf93",
        "moss-80": "#aed2a4",
        "fern-link": "#859984",
        "deep-fern": "#697368",
        "pine-15": "#3e4a3c",
      },
      fontFamily: {
        goga: [
          "Goga",
          "Inter Tight",
          "Space Grotesk",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        inter: [
          "Inter Variable",
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "1.33", letterSpacing: "0.6px" }],
        "body-sm": ["14px", { lineHeight: "1.43", letterSpacing: "-0.364px" }],
        body: ["16px", { lineHeight: "1.5", letterSpacing: "-0.352px" }],
        subheading: ["20px", { lineHeight: "1.5", letterSpacing: "-0.36px" }],
        "heading-sm": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.312px" },
        ],
        heading: ["30px", { lineHeight: "1.2", letterSpacing: "-0.36px" }],
        "heading-lg": [
          "42px",
          { lineHeight: "1.05", letterSpacing: "-0.336px" },
        ],
        display: ["64px", { lineHeight: "1", letterSpacing: "-0.448px" }],
      },
      borderRadius: {
        cards: "8px",
        icons: "0px",
        pills: "9999px",
        inputs: "8px",
        buttons: "12px",
      },
      boxShadow: {
        md: "rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.1) 0px 4px 6px -4px",
      },
      maxWidth: {
        page: "1280px",
      },
      spacing: {
        4: "4px",
        8: "8px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        48: "48px",
        56: "56px",
        64: "64px",
        96: "96px",
        128: "128px",
        160: "160px",
      },
    },
  },
  plugins: [],
};
